first_role = input("Первая роль Джона Галта: ")
second_role = input("Вторая роль Джона Галта: ")
third_role = input("Третья роль Джона Галта: ")
delimiter = input("Разделитель для вывода: ")
print("Who is John Galt?")
print("John Galt is:")
print(first_role, second_role, third_role, sep=delimiter)